### ISSUE TITLE
Missing an easy way to move to next month

### ISSUE THREAD

**Issue by bgbraga** [jessemao/react-calendar-mobile#2]
Hi,

In render I'm missing a easy way to move to next and previous month.
I think it could be done using startDateAt... But I have to implement it, create the arrows < > to move the months, etc...

I good idea is to have that out of box.

**Comment by bgbraga** [comment]
I see that the right way to do that is calling 

`this._calendar.updateCalendarDate( )` passing new date object.

<Calendar> should have that attribute:
`ref={component => this._calendar = component}`

**Comment by jessemao** [comment]
@bgbraga Hi Bruno, 
Thank you for trying out this widget. Yes, I have been thinking about adding arrows to jump between  months and as you mentioned in your post, you can pass values to the calendar's props "startDateAt" to change the months. 

And I will add arrows to next version. 

:)

**Comment by jessemao** [comment]
@bgbraga Hi Bruno,

I just updated to 0.1.4 and now support arrows to change months. :0

**Comment by bgbraga** [comment]
Thanks ;)
