### ISSUE TITLE
日历固定为5周，但有的月在日历上应该是6周

### ISSUE THREAD

**Issue by leecj** [jessemao/react-calendar-mobile#5]
![default](https://user-images.githubusercontent.com/7512945/27209821-be604d0a-5280-11e7-878b-105474fbaf6b.png)
![default](https://user-images.githubusercontent.com/7512945/27209838-d52f1b92-5280-11e7-9948-714a1fb95605.png)

**Comment by jessemao** [comment]
对不起，最近才腾出一点时间来处理这个问题。现在问题已经解决了！
