### ISSUE TITLE
/util/constant.js中item_height

### ISSUE THREAD

**Issue by huan-wang** [jessemao/react-calendar-mobile#6]
请问/util/constant.js中item_height是什么意思？ month是怎样 week又是怎样在移动到手机需要处理兼容性问题，不知道这两个参数的意思

**Comment by jessemao** [comment]
`item_height`指的就是每一行（一周）的高度，所以在月视图中，高度就是 `6 * item_height`.

看[例子](https://jessemao.github.io/react-calendar-mobile/) 中，设置`view`成 `month`就是上面那个月视图，设置成`week`就是下面那个周视图，不知道有没有回答你的问题。
:)

**Comment by huan-wang** [comment]
那请问WEEKDAYS_HEIGHT又是什么意思喃？

**Comment by jessemao** [comment]
`WEEKDAYS_HEIGHT`是第一行周的标题的高度，即`日 一 二 三 四 五 六` 这一行

**Comment by huan-wang** [comment]
请解释一下整个代码滑动的设置，我这边移动到UC国际版样式有问题 我各种跳都不对
